declare type InputElementType = Element | null | undefined;
declare type OutputElementType = Element | null;
declare const find: (selector: string, elm?: InputElementType) => ReadonlyArray<Element>;
declare const findFirst: (selector: string, elm?: InputElementType) => OutputElementType;
declare const is: (elm: InputElementType, selector: string) => boolean;
declare const children: (elm: InputElementType, selector?: string | undefined) => ReadonlyArray<Element>;
declare const contents: (elm: InputElementType) => ReadonlyArray<ChildNode>;
declare const parent: (elm: InputElementType) => OutputElementType;
declare const liesBetween: (elm: InputElementType, highBoundarySelector: string, deepBoundarySelector: string) => boolean;
export { find, findFirst, is, children, contents, parent, liesBetween };
